# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

env:
  APP_NAME: NGFF-Converter
  APP_VERSION: 1.0.3

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    name: package
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - if: ${{ matrix.os == 'macos-latest' }}
      name: Install bundler and download blosc
      run: |
        brew install dylibbundler
        curl -J -O -k -L 'https://github.com/glencoesoftware/c-blosc-macos-x86_64/releases/download/20220919/libblosc.dylib'
    - if: ${{ matrix.os == 'windows-latest' }}
      name: Download blosc
      run: |
        c:\msys64\usr\bin\wget.exe 'https://github.com/glencoesoftware/c-blosc-windows-x86_64/releases/download/20220919/blosc.dll'
    - name: Run jpackage with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: jpackage
    - if: ${{ matrix.os == 'macos-latest' }}
      name: Upload Mac pkg
      uses: actions/upload-artifact@v2
      with:
        path: ./build/jpackage/*.pkg
        name: ${{env.mac_saveas}}
        retention-days: 3
      env:
        mac_saveas: ${{env.APP_NAME}}-${{env.APP_VERSION}}-macos.pkg
    - if: ${{ matrix.os == 'windows-latest' }}
      name: Upload Windows MSI
      uses: actions/upload-artifact@v2
      with:
        path: ./build/jpackage/*.msi
        name: ${{env.win_saveas}}
        retention-days: 3
      env:
        win_saveas: ${{env.APP_NAME}}-${{env.APP_VERSION}}-win.msi
  upload:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    if: startswith(github.ref, 'refs/tags/')
    steps:
      - name: Download Windows installer
        uses: actions/download-artifact@v2
        with:
          name: ${{env.APP_NAME}}-${{env.APP_VERSION}}-win.msi
      - name: Download macOS installer
        uses: actions/download-artifact@v2
        with:
          name: ${{env.APP_NAME}}-${{env.APP_VERSION}}-macos.pkg
      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.msi
            *.pkg
          draft: true
          name: ${{env.APP_NAME}} - ${{env.APP_VERSION}}
          fail_on_unmatched_files: true
